# Generated by Django 2.2.8 on 2020-04-05 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prestador', models.IntegerField(blank=True, null=True)),
                ('numero_prestador_vencimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=12)),
                ('telefono_opcional', models.CharField(blank=True, max_length=12, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('especialidad', models.ManyToManyField(to='profesionales.Especialidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
            },
        ),
    ]
