# Generated by Django 2.2.8 on 2021-03-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_auto_20210304_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='nombre',
        ),
    ]
