# Generated by Django 2.2.8 on 2021-03-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_auto_20210304_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
