# Generated by Django 2.2.8 on 2020-04-05 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obrassociales', '0001_initial'),
        ('profesionales', '0001_initial'),
        ('catalogosenfermedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=12)),
                ('telefono_opcional', models.CharField(blank=True, max_length=12, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_admision', models.DateField(blank=True, null=True)),
                ('medicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fue_al_psicologo', models.CharField(blank=True, max_length=200, null=True)),
                ('grupo_familiar', models.CharField(blank=True, max_length=200, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('diagonostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogosenfermedades.Catalogo')),
                ('profesional_tratante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesionales.Profesional')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='PacienteObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroafiliado', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('obrasocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrassociales.ObraSocial')),
                ('paciente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
            options={
                'verbose_name_plural': 'Pacientes - Obras Sociales',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipodocumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.TipoDocumento'),
        ),
    ]
