# Generated by Django 2.2.8 on 2020-04-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='diagonostico',
            new_name='diagnostico',
        ),
    ]
