# Generated by Django 2.2.8 on 2020-04-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogosenfermedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desripcion', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Fuentes',
            },
        ),
    ]
