# Generated by Django 2.2.8 on 2020-04-06 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogosenfermedades', '0002_fuente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='clave',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='code_0',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='code_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='code_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='code_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='code_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogosenfermedades.Fuente'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
