# Generated by Django 2.2.8 on 2020-04-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogosenfermedades', '0003_auto_20200406_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuente',
            old_name='desripcion',
            new_name='descripcion',
        ),
    ]
