# Generated by Django 2.2.8 on 2020-04-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogosenfermedades', '0004_auto_20200406_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='code',
            new_name='clave',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='code_0',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='code_1',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='code_2',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='code_3',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='code_4',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='nivel',
        ),
        migrations.DeleteModel(
            name='Fuente',
        ),
    ]
