# Generated by Django 4.0.6 on 2025-01-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogosenfermedades', '0005_auto_20200406_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
