# Generated by Django 2.2.8 on 2020-04-05 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nucleador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Nucleadores',
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True)),
                ('abreviatura', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_opcional', models.CharField(blank=True, max_length=12, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prestaciones',
            },
        ),
        migrations.CreateModel(
            name='NucleadorPrestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nucleador', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obrassociales.Nucleador')),
                ('obrasocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrassociales.ObraSocial')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrassociales.Prestacion')),
            ],
            options={
                'verbose_name_plural': 'Nucleadores Prestaciones',
            },
        ),
    ]
