# Generated by Django 2.2.8 on 2020-04-05 23:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
            ],
            options={
                'constraints': [],
                'indexes': [],
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbu', models.CharField(max_length=22)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.Banco')),
                ('tipocuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.TipoCuenta')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.Titular')),
            ],
            options={
                'verbose_name_plural': 'Datos Bancarios',
            },
        ),
    ]
