# Generated by Django 2.2 on 2021-08-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_duracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name_plural': 'Modulo'},
        ),
        migrations.AddField(
            model_name='curso',
            name='presencial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
