# Generated by Django 2.2.8 on 2021-10-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20210817_1629'),
        ('cursos', '0005_curso_modalidad'),
    ]

    operations = [
    ]
