# Generated by Django 2.2.8 on 2021-10-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_merge_20211023_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='valor',
        ),
    ]
