# Generated by Django 2.2.8 on 2021-12-26 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_auto_20211225_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='profesion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.Profesion'),
        ),
    ]
