# Generated by Django 2.2.8 on 2021-12-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alumno_profesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Alumno')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Modulo')),
            ],
            options={
                'verbose_name_plural': 'Inscripccones',
            },
        ),
    ]
