# Generated by Django 2.2.8 on 2021-12-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
