# Generated by Django 2.2.8 on 2021-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_modulo_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='finalizado',
            field=models.BooleanField(),
        ),
    ]
