# Generated by Django 2.2.8 on 2021-12-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_auto_20211226_1129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'modulo')},
        ),
    ]
